
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";


export const metadata = {
  title: "Darts League",
  description: "Generated by Lewis Jelfs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
      
      <Header/>
        
      
        {children}
       
      <Footer/>
      </body>
    </html>
  );
}